package:
  name: cctbx_dependencies
  version: 2019.02.13                   # YYYY.MM.DD

build:
  number: 1

requirements:
  run:
    # basics
    #- python >=2.7
    - cython >=0.27
    #- boost >=1.61
    - numpy >=1.13
    #- scons >=3

    # select LLVM compatible with macOS Xcode
    # https://en.wikipedia.org/wiki/Xcode#Latest_versions
    - libcxx =4.0.1                    # [osx]

    # Python 2/3 compatibility
    - future >=0.16
    - six >=1.11

    # python
    - biopython >=1.68
    - ipython >=3.2.1

    # testing
    - mock >=2.0.0
    - pytest >=3.1,<4
    - pytest-xdist >=1.22

    # documentation
    - docutils >=0.12
    - numpydoc >=0.5
    - sphinx >=1.4.9

    # graphics
    - matplotlib-base
    - pillow >=4.2.1
    - reportlab >=3.4
    #- libpng >=1.5
    #- libtiff >=4.0
    - python.app                        # [osx]
    - gtk2                              # [linux]
    - wxpython
    #- pyside2 =5.6
    - pyopengl =3.1.0

    # HDF5
    - hdf5 >=1.10
    - h5py >=2.7.1
    - hdf5_plugins                      # [unix]

    # other
    - libsvm
    - mrcfile
    - psutil

    # cctbx channel
    - py2app                            # [osx]
    - libsvm_py
    #- hdf5_plugins                      # [unix]

    # dials
    - jinja2 >=2.9.6
    - msgpack-c >=3.1.1
    - msgpack-python >=0.6
    - orderedset >=2.0
    - procrunner
    - python-blosc >=1.7
    - scikit-learn >=0.19.1
    - scipy >=1.0
    - tqdm =4.23.4

    # xia2
    - tabulate

    # control math library
    - nomkl                             # [unix]
    - openblas                          # [unix]

    # Phenix
    - send2trash
    - PyRTF

about:
  home: https://github.com/cctbx/conda_build
  summary: Metapackage for CCTBX dependencies
  description: "This is a metapackage that just installs the dependencies for \
    CCTBX. The conda-forge channel is required."
  doc_url: https://cctbx.github.io/
  dev_url: https://github.com/cctbx/cctbx_project

extra:
  recipe-maintainers:
    - bkpoon
