package:
  name: cctbxlite-deps
  version: 2019.09.01                   # YYYY.MM.DD

build:
  number: 0

requirements:
  run:
    # basics
    #- python >=2.7
    - cython
    #- boost >=1.61
    - numpy
    #- scons >=3

    # select LLVM compatible with macOS Xcode
    # https://en.wikipedia.org/wiki/Xcode#Latest_versions
    - libcxx =4.0.1                    # [osx]

    # Python 2/3 compatibility
    - future
    - six

    # python
    - biopython
    - ipython

    # testing
    - mock
    - pytest
    - pytest-xdist

    # documentation
    - docutils
    - numpydoc
    - sphinx

    # graphics
    - matplotlib-base
    - pillow
    - reportlab
    - python.app                        # [osx]
    - gtk2                              # [linux]
    - wxpython
    - pyopengl =3.1.0

    # other
    - libsvm
    - mrcfile
    - psutil

    # cctbx channel
    - py2app                            # [osx]
    - libsvm_py
    #- hdf5_plugins                      # [unix]

    # control math library
    - nomkl                             # [unix]
    - openblas                          # [unix]

    # # dials
    # - jinja2 >=2.9.6
    # - msgpack-c >=3.1.1
    # - msgpack-python >=0.6
    # - orderedset >=2.0
    # - procrunner
    # - python-blosc >=1.7
    # - scikit-learn >=0.19.1
    # - scipy >=1.0
    # - tqdm =4.23.4

    # # xia2
    # - tabulate

    # # Phenix
    # - send2trash
    # - PyRTF

test:
  imports:
    - numpy
    - six

outputs:
  - name: cctbxlite-deps

  - name: cctbx-deps
    requirements:
      run:
        - {{ pin_subpackage('cctbxlite-deps', exact=True) }}

        # HDF5
        - hdf5
        - h5py
        - hdf5_plugins                      # [unix]

        # other
        - pyzmq
        - websocket-server

about:
  home: https://github.com/cctbx/conda_build
  summary: Metapackage for CCTBX dependencies
  description: "This is a metapackage that just installs the dependencies for \
    CCTBX. The conda-forge channel is required."
  doc_url: https://cctbx.github.io/
  dev_url: https://github.com/cctbx/cctbx_project

extra:
  recipe-maintainers:
    - bkpoon
